In [1]:
import numpy as np

data=np.arange(11,30,2)
print(data)
print(data.ndim)
print(data.size)

[11 13 15 17 19 21 23 25 27 29]
1
10

In [2]:
data=np.arange(5,36,7)
data

array([ 5, 12, 19, 26, 33])

In [3]:
data=np.full((4,3),9)
data

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [4]:
a=np.array([6,12,18,24])
remainder=a%5
remainder

array([1, 2, 3, 4])

In [5]:
arr=np.array([14,28,42,56,70,84])
extract=arr[[1,3,5]]
extract

array([28, 56, 84])

In [6]:
arr=np.array([-16,25,-36,49])
abs_data=np.abs(arr)
sqrt_data=np.sqrt(abs_data)
print(abs_data)
print(sqrt_data)

[16 25 36 49]
[4. 5. 6. 7.]

In [7]:
arr=np.arange(7,13).reshape(3,2)
print(arr)
print(arr.ndim)
print(arr.T)
print(arr.ndim)

[[ 7  8]
 [ 9 10]
 [11 12]]
2
[[ 7  9 11]
 [ 8 10 12]]
2

In [8]:
temperatures=np.array([18,22,27,31,24,19])
Temperature_Range=np.max(temperatures)-np.min(temperatures)
Median_temperature=np.median(arr)
print(Temperature_Range)
print(Median_temperature)

13
9.5

In [9]:
values=np.array([4,9,4,2,9,7,2,4])
unique_values=np.unique(values)
print(unique_values)
count_unique_values=len(unique_values)
print(count_unique_values)

[2 4 7 9]
4

In [10]:
speed=np.array([35,62,48,81,55])
categories=np.where(speed>=60,'Fast','Normal')
print(categories)

['Normal' 'Fast' 'Normal' 'Fast' 'Normal']

In [11]:
import pandas as pd
Books_Issued=pd.Series([24,31,19,27],index=['Monday','Tuesday','Wednesday','Thursday'])
Books_Issued

Monday       24
Tuesday      31
Wednesday    19
Thursday     27
dtype: int64

In [12]:
prices = pd.Series([45000, 18000, 22000], index=['Laptop', 'Tablet', 'Phone'])

tablet_price = prices['Tablet']
print("Tablet Price:", tablet_price)

Tablet Price: 18000

In [13]:
rainfall=pd.Series([12,0,18,5,23])
rainfall_measurement=rainfall[rainfall>10]
rainfall_measurement.rename('Rainfall Measurment',inplace=True)
rainfall_measurement

0    12
2    18
4    23
Name: Rainfall Measurment, dtype: int64

In [14]:
data = {
    'Gold': 7200,
    'Silver': 95,
    'Copper': 850
}

s = pd.Series(data)

print("Index:")
print(s.index)

print("Values:")
print(s.values)

Index:
Index(['Gold', 'Silver', 'Copper'], dtype='object')
Values:
[7200   95  850]

In [15]:
ratings = pd.Series([3.5, 4.2, 2.8, 4.7])

ratings.name = "Customer Ratings"

ratings.index.name = "Review ID"

print(ratings)

Review ID
0    3.5
1    4.2
2    2.8
3    4.7
Name: Customer Ratings, dtype: float64

In [16]:
s = pd.Series([11, 22, 33], index=['X1', 'X2', 'X3'])

print("X2 exists:", "X2" in s.index)

print("X4 is absent:", "X4" not in s.index)

X2 exists: True
X4 is absent: True

In [17]:
stock = pd.Series(
    [16, 28, 12],
    index=['Keyboard', 'Mouse', 'Monitor']
)
result = stock.to_dict()
print(result)

{'Keyboard': 16, 'Mouse': 28, 'Monitor': 12}

In [18]:
data = {'Hindi': 78,'English': 84,'Computer': 91}

s = pd.Series(data, index=['Computer', 'Hindi', 'Art', 'English'])

print(s)

Computer    91.0
Hindi       78.0
Art          NaN
English     84.0
dtype: float64

In [19]:
expenses = pd.Series([1200, None, 850, None, 600])
print(expenses.isnull())
print(expenses.notnull())

0    False
1     True
2    False
3     True
4    False
dtype: bool
0     True
1    False
2     True
3    False
4     True
dtype: bool

In [20]:
a = pd.Series([8, 15, 22], index=['P', 'Q', 'R'])

b = pd.Series([4, 6, 10], index=['R', 'P', 'Q'])

result = a + b

print(result)

P    14
Q    25
R    26
dtype: int64

In [21]:
sales = np.array([[120, 150, 180],[140, 160, 175],[135, 155, 190],[150, 170, 200]])

daily_sales = np.sum(sales, axis=1)

product_sales = np.sum(sales, axis=0)

print("Total sales for each day:")
print(daily_sales)

print("Total sales for each product:")
print(product_sales)

print("Highest sales day:", np.argmax(daily_sales) + 1)

Total sales for each day:
[450 475 480 520]
Total sales for each product:
[545 635 745]
Highest sales day: 4

In [22]:
a = np.arange(10, 46).reshape(6, 6)
print(a)
sub = a[2:6, 1:5]
print(sub)
print("Mean:", np.mean(sub))

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]
 [40 41 42 43 44 45]]
[[23 24 25 26]
 [29 30 31 32]
 [35 36 37 38]
 [41 42 43 44]]
Mean: 33.5

In [23]:
weights = np.array([48, 62, 75, 81, 54, 69, 90])
above_70 = weights[weights > 70]
print(above_70)
new_weights = np.where(weights < 55, 55, weights)
print(new_weights)
print(weights)

[75 81 90]
[55 62 75 81 55 69 90]
[48 62 75 81 54 69 90]

In [24]:
quantity = np.array([3, 5, 2, 7])
price = np.array([120, 80, 250, 60])
cost = quantity * price
total_bill = np.sum(cost)
percentage = (cost / total_bill) * 100
print("Product Cost:", cost)
print("Overall Bill:", total_bill)
print("Percentage Contribution:", percentage)

Product Cost: [360 400 500 420]
Overall Bill: 1680
Percentage Contribution: [21.42857143 23.80952381 29.76190476 25.        ]

In [25]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Row Variance:")
print(np.var(a, axis=1))
print("Row Standard Deviation:")
print(np.std(a, axis=1))
print("Column Variance:")
print(np.var(a, axis=0))
print("Column Standard Deviation:")
print(np.std(a, axis=0))

Row Variance:
[1.25 1.25 1.25]
Row Standard Deviation:
[1.11803399 1.11803399 1.11803399]
Column Variance:
[10.66666667 10.66666667 10.66666667 10.66666667]
Column Standard Deviation:
[3.26598632 3.26598632 3.26598632 3.26598632]

In [26]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[7, 8],[9, 10],[11, 12]])
result = np.dot(a, b)
print(result)

[[ 58  64]
 [139 154]]

In [27]:
a = np.random.randint(10, 100, 25)
print(a)
sorted_array = np.sort(a)
print(sorted_array)
print(sorted_array[-5:])
print(len(np.unique(a)))

[16 76 84 85 32 12 50 71 62 23 13 36 80 61 81 34 53 15 73 50 45 27 12 87
 61]
[12 12 13 15 16 23 27 32 34 36 45 50 50 53 61 61 62 71 73 76 80 81 84 85
 87]
[80 81 84 85 87]
22

In [28]:
a = np.array([5, 10, 15, 20, 25, 30])
b = a[1:5]
c = a[1:5].copy()
b[1] = 99
c[2] = 77
print("a =", a)
print("b =", b)
print("c =", c)

a = [ 5 10 99 20 25 30]
b = [10 99 20 25]
c = [10 15 77 25]

In [29]:
dept_a = pd.Series({'Jan': 250,'Feb': 310,'Mar': 290})
dept_b = pd.Series({'Mar': 180,'Jan': 210,'Apr': 260})
result = dept_a + dept_b
result

Apr      NaN
Feb      NaN
Jan    460.0
Mar    470.0
dtype: float64

In [30]:
attendance = pd.Series([82, 67, 91, 74, 58],index=['S101', 'S102', 'S103', 'S104', 'S105'])
result = attendance[attendance < 75]
print("Students below 75%:")
print(result)
print("Student Labels:")
print(result.index)
print("Total Students:")
print(result.count())

Students below 75%:
S102    67
S104    74
S105    58
dtype: int64
Student Labels:
Index(['S102', 'S104', 'S105'], dtype='object')
Total Students:
3

In [31]:
inventory = {'Pen': 50,'Pencil': 80,'Eraser': 40,'Scale': 25}
labels = ['Scale', 'Pen', 'Marker', 'Eraser']
s = pd.Series(inventory, index=labels)
print(s)

Scale     25.0
Pen       50.0
Marker     NaN
Eraser    40.0
dtype: float64

In [32]:
s1 = pd.Series([100, 200, 300],index=['North', 'South', 'East'])
s2 = pd.Series([10, 20, 30],index=['South', 'West', 'North'])
result = s1 - s2
print(result)
print(result[result.notnull()])

East       NaN
North     70.0
South    190.0
West       NaN
dtype: float64
North     70.0
South    190.0
dtype: float64

In [33]:
consumption = pd.Series([220, 310, 275, 190, 360],index=['Household A','Household B','Household C','Household D','Household E'])

print("Original Series:")
print(consumption)
filtered = consumption[consumption > 250]
print("Filtered Series:")
print(filtered)
data = filtered.to_dict()
print("Dictionary:")
print(data)
new_series = pd.Series(data)
print("New Series:")
print(new_series)

Original Series:
Household A    220
Household B    310
Household C    275
Household D    190
Household E    360
dtype: int64
Filtered Series:
Household B    310
Household C    275
Household E    360
dtype: int64
Dictionary:
{'Household B': 310, 'Household C': 275, 'Household E': 360}
New Series:
Household B    310
Household C    275
Household E    360
dtype: int64

In [34]:
s = pd.Series({'A': 45, 'B': 70, 'C': 55},index=['C', 'D', 'A', 'B'])
s.name = 'Performance'
s.index.name = 'Group'
print("Original Series:")
print(s)
print("Values >= 50:")
print(s[s >= 50])
print("Missing Values:")
print(s[s.isnull()])
print("Series Name:", s.name)
print("Index Name:", s.index.name)

Original Series:
Group
C    55.0
D     NaN
A    45.0
B    70.0
Name: Performance, dtype: float64
Values >= 50:
Group
C    55.0
B    70.0
Name: Performance, dtype: float64
Missing Values:
Group
D   NaN
Name: Performance, dtype: float64
Series Name: Performance
Index Name: Group

In [35]:
np.random.seed(42)

marks = np.random.randint(20, 101, size=(12, 4))
print("Student Marks:")
print(marks)
student_avg = np.mean(marks, axis=1)
print("Student Averages:")
print(student_avg)
test_mean = np.mean(marks, axis=0)
print("Test Mean:")
print(test_mean)
test_std = np.std(marks, axis=0)
print("Test Standard Deviation:")
print(test_std)
passed = np.all(marks >= 40, axis=1)
print("Students passing all tests:")
print(np.where(passed)[0] + 1)
high_avg = np.where(student_avg >= 75)[0] + 1
print("Students with average >= 75:")
print(high_avg)
max_variation = np.argmax(test_std) + 1
print("Test with greatest variation:")
print(max_variation)

Student Marks:
[[71 34 91 80]
 [40 94 94 43]
 [22 41 72 21]
 [49 57 21 83]
 [79 40 52 95]
 [77 41 68 78]
 [61 79 99 34]
 [81 81 66 81]
 [70 74 83 22]
 [70 26 40 92]
 [58 37 23 79]
 [33 28 72 21]]
Student Averages:
[69.   67.75 39.   52.5  66.5  66.   68.25 77.25 62.25 57.   49.25 38.5 ]
Test Mean:
[59.25       52.66666667 65.08333333 60.75      ]
Test Standard Deviation:
[18.49380527 22.40659625 25.16432108 28.50182743]
Students passing all tests:
[2 5 6 8]
Students with average >= 75:
[8]
Test with greatest variation:
4

In [36]:
np.random.seed(42)
marks = np.random.randint(20, 101, (12, 4))
print(marks)

[[71 34 91 80]
 [40 94 94 43]
 [22 41 72 21]
 [49 57 21 83]
 [79 40 52 95]
 [77 41 68 78]
 [61 79 99 34]
 [81 81 66 81]
 [70 74 83 22]
 [70 26 40 92]
 [58 37 23 79]
 [33 28 72 21]]

In [37]:
student_avg = marks.mean(axis=1)
print(student_avg)

[69.   67.75 39.   52.5  66.5  66.   68.25 77.25 62.25 57.   49.25 38.5 ]

In [38]:
test_mean = marks.mean(axis=0)
test_std = marks.std(axis=0)
print("Mean:", test_mean)
print("Standard Deviation:", test_std)

Mean: [59.25       52.66666667 65.08333333 60.75      ]
Standard Deviation: [18.49380527 22.40659625 25.16432108 28.50182743]

In [39]:
passed = np.all(marks >= 40, axis=1)
print(passed.sum())

4

In [40]:
students = np.where(student_avg >= 75)[0] + 1
print(students)

[8]

In [41]:
print(np.argmax(test_std) + 1)

4

In [42]:
a = np.arange(21, 46).reshape(5, 5)

print(a)

[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]]

In [43]:
b = a[1:4, 1:4]

print(b)

[[27 28 29]
 [32 33 34]
 [37 38 39]]

In [44]:
c = b.T
print(c)

[[27 32 37]
 [28 33 38]
 [29 34 39]]

In [45]:
d = b @ c
print(d)

[[2354 2774 3194]
 [2774 3269 3764]
 [3194 3764 4334]]

In [46]:
row_sum = d.sum(axis=1)
print(row_sum)

[ 8322  9807 11292]

In [47]:
print("Maximum:", d.max())
print("Position:", np.argwhere(d == d.max()))

Maximum: 4334
Position: [[2 2]]

In [48]:
quantity = np.array([[10, 20, 15, 8],[12, 18, 20, 10],[15, 25, 12, 9],[20, 15, 18, 12],[18, 22, 16, 11],[25, 20, 14, 15]])
price = np.array([150, 240, 90, 320])

In [49]:
daily_revenue = quantity @ price
print(daily_revenue)

[10210 11120 12210 12060 12940 14610]

In [50]:
total_quantity = quantity.sum(axis=0)
print(total_quantity)

[100 120  95  65]

In [51]:
total_revenue = daily_revenue.sum()
print(total_revenue)

73150

In [52]:
day = np.argmax(daily_revenue) + 1
print(day)

6

In [53]:
best_product = np.argmax(total_quantity) + 1
print(best_product)

2

In [54]:
new_price = price.astype(float).copy()
new_price[total_quantity > 100] *= 0.90
print(new_price)

[150. 216.  90. 320.]

In [55]:
new_daily_revenue = quantity @ new_price
print(new_daily_revenue)
print("New Total Revenue:", new_daily_revenue.sum())

[ 9730. 10688. 11610. 11700. 12412. 14130.]
New Total Revenue: 70270.0

In [56]:
np.random.seed(42)
data = np.random.normal(50, 12, 100)
print(data)

[55.96056984 48.34082839 57.77226246 68.27635828 47.1901595  47.19035652
 68.95055379 59.20921675 44.36630737 56.51072052 44.43898769 44.41124296
 52.90354726 27.04063706 29.30098601 43.25254965 37.84602656 53.77096799
 39.10371109 33.05235558 67.58778523 47.29068439 50.81033846 32.90302177
 43.46740731 51.33107108 36.18807707 54.50837622 42.79233572 46.499675
 42.77952065 72.22733821 49.8380333  37.30746885 59.87053895 35.3498762
 52.50636314 26.48395851 34.06176741 52.36233483 58.86159896 52.05641937
 48.61222061 46.38675565 32.25773612 41.3618695  44.47233475 62.68546671
 54.12341947 28.84351814 53.88900763 45.37901264 41.876936   57.34011547
 62.37199427 61.17536143 39.92938972 46.28945149 53.97516118 61.70654153
 44.24990915 47.77209228 36.72398031 35.64552051 59.75030987 66.27488034
 49.13587854 62.04239477 54.3396323  42.25856294 54.33674727 68.4564388
 49.57008753 68.77572387 18.56305875 59.86283005 51.04456482 46.41191179
 51.10112932 26.14917302 47.36393735 54.28535086 67.73472854 43.78075738
 40.29807677 43.97891548 60.98482541 53.94501332 43.64287755 56.1592092
 51.16493059 61.62373989 41.57536287 46.06805424 45.29470216 32.43782062
 53.55344332 53.13266327 50.06136148 47.1849544 ]

In [57]:
cleaned = np.where(
    data < 30, 30,
    np.where(data > 70, 70, data)
)

print(cleaned)

[55.96056984 48.34082839 57.77226246 68.27635828 47.1901595  47.19035652
 68.95055379 59.20921675 44.36630737 56.51072052 44.43898769 44.41124296
 52.90354726 30.         30.         43.25254965 37.84602656 53.77096799
 39.10371109 33.05235558 67.58778523 47.29068439 50.81033846 32.90302177
 43.46740731 51.33107108 36.18807707 54.50837622 42.79233572 46.499675
 42.77952065 70.         49.8380333  37.30746885 59.87053895 35.3498762
 52.50636314 30.         34.06176741 52.36233483 58.86159896 52.05641937
 48.61222061 46.38675565 32.25773612 41.3618695  44.47233475 62.68546671
 54.12341947 30.         53.88900763 45.37901264 41.876936   57.34011547
 62.37199427 61.17536143 39.92938972 46.28945149 53.97516118 61.70654153
 44.24990915 47.77209228 36.72398031 35.64552051 59.75030987 66.27488034
 49.13587854 62.04239477 54.3396323  42.25856294 54.33674727 68.4564388
 49.57008753 68.77572387 30.         59.86283005 51.04456482 46.41191179
 51.10112932 30.         47.36393735 54.28535086 67.73472854 43.78075738
 40.29807677 43.97891548 60.98482541 53.94501332 43.64287755 56.1592092
 51.16493059 61.62373989 41.57536287 46.06805424 45.29470216 32.43782062
 53.55344332 53.13266327 50.06136148 47.1849544 ]

In [58]:
print("Original Mean:", data.mean())
print("Original Variance:", data.var())
print("Original Standard Deviation:", data.std())
print("Original Minimum:", data.min())
print("Original Maximum:", data.max())

Original Mean: 48.75384179127088
Original Variance: 117.57919603591557
Original Standard Deviation: 10.843394119735553
Original Minimum: 18.56305875092307
Original Maximum: 72.22733821410725

In [59]:
print("Cleaned Mean:", cleaned.mean())
print("Cleaned Variance:", cleaned.var())
print("Cleaned Standard Deviation:", cleaned.std())
print("Cleaned Minimum:", cleaned.min())
print("Cleaned Maximum:", cleaned.max())

Cleaned Mean: 48.967755094142284
Cleaned Variance: 105.99277431898325
Cleaned Standard Deviation: 10.295279224915818
Cleaned Minimum: 30.0
Cleaned Maximum: 70.0

In [60]:
branch_a = pd.Series({'Q1': 120,'Q2': 145,'Q4': 180})
branch_b = pd.Series({'Q2': 110,'Q3': 135,'Q4': 155})
branch_c = pd.Series({'Q1': 95,'Q3': 125,'Q4': 140})

In [61]:
result = branch_a + branch_b + branch_c
print(result)

Q1      NaN
Q2      NaN
Q3      NaN
Q4    475.0
dtype: float64

In [62]:
common = (branch_a.index.intersection(branch_b.index).intersection(branch_c.index))
print(common)

Index(['Q4'], dtype='object')

In [63]:
print(result.loc[common])

Q4    475.0
dtype: float64

In [64]:
total = (branch_a.add(branch_b, fill_value=0).add(branch_c, fill_value=0))
print(total)

Q1    215.0
Q2    255.0
Q3    260.0
Q4    475.0
dtype: float64

In [65]:
scores = {
    'R101': 78,
    'R102': 65,
    'R104': 92,
    'R105': 48
}

required = [
    'R105', 'R103', 'R101',
    'R106', 'R104', 'R102'
]

s = pd.Series(scores, index=required)

print(s)

R105    48.0
R103     NaN
R101    78.0
R106     NaN
R104    92.0
R102    65.0
dtype: float64

In [66]:
print(s.isnull())

R105    False
R103     True
R101    False
R106     True
R104    False
R102    False
dtype: bool

In [67]:
valid = s[s.notnull() & (s >= 70)]

print(valid)

R101    78.0
R104    92.0
dtype: float64

In [68]:
d = filtered.to_dict()

print(d)

{'Household B': 310, 'Household C': 275, 'Household E': 360}

In [69]:
print(filtered.equals(new_s))

NameError: name 'new_s' is not defined