In [4]:
 import pandas as pd
import numpy as np
student_data={'Name' :['Ram','Krishna','Radha','Hari'], 'Age':[19,20,21,22], 'City': ['Ayodhya','Vrindavan','Barsana','Vaikunth'] }
student_df=pd.DataFrame(student_data)
student_df

      Name  Age       City
0      Ram   19    Ayodhya
1  Krishna   20  Vrindavan
2    Radha   21    Barsana
3     Hari   22   Vaikunth

In [5]:
student_df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [6]:
student_df['Name']

0        Ram
1    Krishna
2      Radha
3       Hari
Name: Name, dtype: object

In [7]:
student_df['City']

0      Ayodhya
1    Vrindavan
2      Barsana
3     Vaikunth
Name: City, dtype: object

In [8]:
name_city=pd.DataFrame(student_df,columns=['Name','City'])
name_city

      Name       City
0      Ram    Ayodhya
1  Krishna  Vrindavan
2    Radha    Barsana
3     Hari   Vaikunth

In [9]:
book_data = {
    'Book': ['Python Basics', 'Data Science', 'Machine Learning'],
    'Author': ['John', 'David', 'Smith'],
    'Price': [300, 450, 600]
}

book_df = pd.DataFrame(book_data)

book_df

               Book Author  Price
0     Python Basics   John    300
1      Data Science  David    450
2  Machine Learning  Smith    600

In [10]:
book_df['Publisher'] = 'ABC Publications'

book_df

               Book Author  Price         Publisher
0     Python Basics   John    300  ABC Publications
1      Data Science  David    450  ABC Publications
2  Machine Learning  Smith    600  ABC Publications

In [11]:
df = pd.DataFrame({
    'Name': ['A', 'B', 'C', 'D', 'E']
})

df['SerialNo'] = np.arange(5)

df

  Name  SerialNo
0    A         0
1    B         1
2    C         2
3    D         3
4    E         4

In [12]:
del df['SerialNo']

df

  Name
0    A
1    B
2    C
3    D
4    E

In [13]:
movie_data={'Movie' :['Interstellar','Apollo 13','Mission Mars','Gravity'], 'Year':[2014,1995,2017,2019], 'Rating':[9.8,8.8,8.6,8.3]}
movie_df=pd.DataFrame(movie_data)
movie_df

          Movie  Year  Rating
0  Interstellar  2014     9.8
1     Apollo 13  1995     8.8
2  Mission Mars  2017     8.6
3       Gravity  2019     8.3

In [14]:
movie2_data={'Movie' :['Lost in Space','Asteroid Comes Home','Space Monster','Alien World'],'Ratings':[8.2,8.5,9.2,9.5]}
movie2_df=pd.DataFrame(movie2_data)
movie2_df['Director']=['Kevin Walsh','Christopher Nolan','Bill Clington','Mathew Stokes']
movie2_df

                 Movie  Ratings           Director
0        Lost in Space      8.2        Kevin Walsh
1  Asteroid Comes Home      8.5  Christopher Nolan
2        Space Monster      9.2      Bill Clington
3          Alien World      9.5      Mathew Stokes

In [15]:
city_data=pd.Series(['Vrindavan','Barsana'],index=[0,3])
city_data

0    Vrindavan
3      Barsana
dtype: object

In [16]:
branch_df=pd.DataFrame({'Name' :['Ram','Krishna','Radha','Hari']})
branch_df['City']=city_data
branch_df

      Name       City
0      Ram  Vrindavan
1  Krishna        NaN
2    Radha        NaN
3     Hari    Barsana

In [17]:
Employee_df=pd.DataFrame({'Employee': ['Aman', 'Riya', 'Rahul', 'Priya', 'Karan'],
    'Department': ['IT', 'HR', 'Finance', 'IT', 'Sales'],
    'Experience': [2, 4, 3, 5, 1]
})
Employee_new_df=Employee_df[['Employee','Experience']]
Employee_new_df

  Employee  Experience
0     Aman           2
1     Riya           4
2    Rahul           3
3    Priya           5
4    Karan           1

In [18]:
Employee_df['Department']

0         IT
1         HR
2    Finance
3         IT
4      Sales
Name: Department, dtype: object

In [19]:
Employee_df.columns

Index(['Employee', 'Department', 'Experience'], dtype='object')

In [20]:
Employee_df[['Office']]=['Head Office']
Employee_df

  Employee Department  Experience       Office
0     Aman         IT           2  Head Office
1     Riya         HR           4  Head Office
2    Rahul    Finance           3  Head Office
3    Priya         IT           5  Head Office
4    Karan      Sales           1  Head Office

In [21]:
Employee_df['Office']=np.arange(5)
Employee_df

  Employee Department  Experience  Office
0     Aman         IT           2       0
1     Riya         HR           4       1
2    Rahul    Finance           3       2
3    Priya         IT           5       3
4    Karan      Sales           1       4

In [22]:
Office_Names=pd.Series(['Delhi','Mumbai','Pune'],index=[0,2,4])
Employee_df['Office']=Office_Names
Employee_df

  Employee Department  Experience  Office
0     Aman         IT           2   Delhi
1     Riya         HR           4     NaN
2    Rahul    Finance           3  Mumbai
3    Priya         IT           5     NaN
4    Karan      Sales           1    Pune

In [23]:
del Employee_df['Office']
Employee_df

  Employee Department  Experience
0     Aman         IT           2
1     Riya         HR           4
2    Rahul    Finance           3
3    Priya         IT           5
4    Karan      Sales           1

In [24]:
product_data = {
    'Product': ['Laptop', 'Phone', 'Tablet'],
    'Category': ['Electronics', 'Electronics', 'Electronics'],
    'Price': [50000, 30000, 20000]
}

product_df = pd.DataFrame(product_data)

product_new_df = product_df[['Price', 'Product', 'Category']]

product_new_df

   Price Product     Category
0  50000  Laptop  Electronics
1  30000   Phone  Electronics
2  20000  Tablet  Electronics

In [25]:
data = {
    'Name': ['Aman', 'Riya', 'Rahul'],
    'Age': [20, 21, 19],
    'City': ['Delhi', 'Mumbai', 'Pune']
}

df = pd.DataFrame(data)

new_df = pd.DataFrame(
    df,
    columns=['Name', 'Age', 'City', 'Salary']
)

new_df

    Name  Age    City  Salary
0   Aman   20   Delhi     NaN
1   Riya   21  Mumbai     NaN
2  Rahul   19    Pune     NaN

In [26]:
marks_df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rahul'],
    'Total Marks': [85, 92, 78]
})

marks_df['Total Marks']

0    85
1    92
2    78
Name: Total Marks, dtype: int64

In [27]:
course_data = {
    'Student': ['Aman', 'Riya', 'Rahul', 'Priya', 'Karan'],
    'Course': ['Python', 'Pandas', 'Python', 'NumPy', 'Pandas'],
    'Score': [85, 90, 78, 88, 95]
}

course_df = pd.DataFrame(course_data)

In [28]:
course_df.columns

Index(['Student', 'Course', 'Score'], dtype='object')

In [29]:
course_df['Student']

0     Aman
1     Riya
2    Rahul
3    Priya
4    Karan
Name: Student, dtype: object

In [30]:
course_score_df = course_df[['Student', 'Score']]

course_score_df

  Student  Score
0    Aman     85
1    Riya     90
2   Rahul     78
3   Priya     88
4   Karan     95

In [31]:
course_df['Batch'] = '2026'
course_df

  Student  Course  Score Batch
0    Aman  Python     85  2026
1    Riya  Pandas     90  2026
2   Rahul  Python     78  2026
3   Priya   NumPy     88  2026
4   Karan  Pandas     95  2026

In [32]:
travel_df = pd.DataFrame({
    'Destination': ['Delhi', 'Agra', 'Jaipur', 'Mumbai', 'Goa']})
travel_df['Code'] = np.arange(5)
travel_df

  Destination  Code
0       Delhi     0
1        Agra     1
2      Jaipur     2
3      Mumbai     3
4         Goa     4

In [33]:
travel_df['Code'] = pd.Series({1: 101, 4: 104})
travel_df

  Destination   Code
0       Delhi    NaN
1        Agra  101.0
2      Jaipur    NaN
3      Mumbai    NaN
4         Goa  104.0

In [34]:
data = {
    'Student': ['Aman', 'Riya', 'Rahul', 'Priya', 'Neha'],
    'Class': [10, 10, 12, 11, 12],
    'Section': ['A', 'B', 'A', 'C', 'B']
}

school_df = pd.DataFrame(data,columns=['Student', 'Class', 'Section', 'House'])

school_df

  Student  Class Section House
0    Aman     10       A   NaN
1    Riya     10       B   NaN
2   Rahul     12       A   NaN
3   Priya     11       C   NaN
4    Neha     12       B   NaN

In [35]:
school_df['House'] = 'Blue'
school_df

  Student  Class Section House
0    Aman     10       A  Blue
1    Riya     10       B  Blue
2   Rahul     12       A  Blue
3   Priya     11       C  Blue
4    Neha     12       B  Blue

In [37]:
inventory_df = pd.DataFrame({
    'Item': ['Pen', 'Book', 'Pencil', 'Eraser', 'Ruler'],
    'Quantity': [20, 15, 30, 25, 10],
    'Price': [10, 50, 5, 8, 15]
})
inventory_df['Discount'] = pd.Series({1: 5, 3: 10})
print(inventory_df)
del inventory_df['Discount']
inventory_df

     Item  Quantity  Price  Discount
0     Pen        20     10       NaN
1    Book        15     50       5.0
2  Pencil        30      5       NaN
3  Eraser        25      8      10.0
4   Ruler        10     15       NaN

     Item  Quantity  Price
0     Pen        20     10
1    Book        15     50
2  Pencil        30      5
3  Eraser        25      8
4   Ruler        10     15

In [38]:
import pandas as pd

lab_df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rahul', 'Priya'],
    'Age': [20, 21, 19, 22],
    'Course Name': ['Python', 'Java', 'C++', 'Python'],
    'Marks': [85, 90, 78, 92]
})
lab_df
lab_df.columns
lab_df['Name']
lab_df['Course Name']
small_df = lab_df[['Name', 'Marks']]
small_df
lab_df['Batch'] = 2026
lab_df
del lab_df['Batch']
lab_df

    Name  Age Course Name  Marks
0   Aman   20      Python     85
1   Riya   21        Java     90
2  Rahul   19         C++     78
3  Priya   22      Python     92